apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 22
      name: ssh
    - port: 80
      name: http
    - port: 443
      name: https
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ft_services_nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 22
              name: ssh
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
