FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS wordpress;

CREATE USER 'cowboy'@'%' IDENTIFIED BY 'pass';
GRANT ALL PRIVILEGES ON *.* TO 'cowboy'@'%' IDENTIFIED BY 'pass' WITH GRANT OPTION;

FLUSH PRIVILEGES;