FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS wordpress;

CREATE USER 'keymaster'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'keymaster'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;

CREATE USER 'wp_user'@'%' IDENTIFIED BY 'wp_pass';
GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_user'@'%' IDENTIFIED BY 'wp_pass' WITH GRANT OPTION;

FLUSH PRIVILEGES;
